
logging:
  level:
    org:
      springframework:
        web: INFO
        security: INFO
   
server:
  port: 8083

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: banque
      